[package]
name = "flowagent-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
thiserror = { workspace = true }
serde_json = { version = "1", features = ["raw_value"] }
serde_repr = "0.1"
serde = { workspace = true }
derive-new = { workspace = true }
crossbeam = "0.8.4"
